#include <windows.h>
#include <shellapi.h>
#include <bcrypt.h>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>

namespace {
struct Args{DWORD pid=0;std::wstring readyEvent,installer,version;unsigned long long size=0;std::string sha;};
std::wstring logPath(){wchar_t p[32768]{};DWORD n=GetEnvironmentVariableW(L"LOCALAPPDATA",p,DWORD(std::size(p)));if(!n||n>=std::size(p))return{};auto folder=std::filesystem::path(std::wstring(p,n))/L"RearSilver Avatar"/L"Updates";std::error_code e;std::filesystem::create_directories(folder,e);return(folder/L"updater.log").wstring();}
void log(const std::wstring&m){auto p=logPath();if(p.empty())return;SYSTEMTIME t{};GetLocalTime(&t);std::wofstream o(std::filesystem::path(p),std::ios::app);if(o)o<<t.wYear<<L'-'<<t.wMonth<<L'-'<<t.wDay<<L' '<<t.wHour<<L':'<<t.wMinute<<L':'<<t.wSecond<<L" PID="<<GetCurrentProcessId()<<L' '<<m<<L'\n';}
void fail(const wchar_t*m){log(std::wstring(L"error: ")+m);MessageBoxW(nullptr,m,L"RearSilver Avatar Suite Updater",MB_OK|MB_ICONERROR);}
bool parse(Args&a){int count=0;LPWSTR*v=CommandLineToArgvW(GetCommandLineW(),&count);if(!v)return false;for(int i=1;i<count;++i){std::wstring k=v[i];auto next=[&]{return i+1<count?std::wstring(v[++i]):std::wstring{};};if(k==L"--avatar-pid")a.pid=wcstoul(next().c_str(),nullptr,10);else if(k==L"--ready-event")a.readyEvent=next();else if(k==L"--installer")a.installer=next();else if(k==L"--version")a.version=next();else if(k==L"--size")a.size=_wcstoui64(next().c_str(),nullptr,10);else if(k==L"--sha256"){auto w=next();a.sha.clear();for(const wchar_t c:w){if(!((c>=L'0'&&c<=L'9')||(c>=L'a'&&c<=L'f'))){LocalFree(v);return false;}a.sha.push_back(static_cast<char>(c));}}else{LocalFree(v);return false;}}LocalFree(v);return a.pid&& !a.readyEvent.empty()&&!a.installer.empty()&&!a.version.empty()&&a.size&&a.sha.size()==64;}
std::string sha256(const std::wstring&path){BCRYPT_ALG_HANDLE alg=nullptr;BCRYPT_HASH_HANDLE hash=nullptr;DWORD ob=0,hb=0,n=0;std::vector<unsigned char>obj,digest;if(BCryptOpenAlgorithmProvider(&alg,BCRYPT_SHA256_ALGORITHM,nullptr,0)<0)return{};if(BCryptGetProperty(alg,BCRYPT_OBJECT_LENGTH,(PUCHAR)&ob,sizeof(ob),&n,0)<0||BCryptGetProperty(alg,BCRYPT_HASH_LENGTH,(PUCHAR)&hb,sizeof(hb),&n,0)<0){BCryptCloseAlgorithmProvider(alg,0);return{};}obj.resize(ob);digest.resize(hb);if(BCryptCreateHash(alg,&hash,obj.data(),DWORD(obj.size()),nullptr,0,0)<0){BCryptCloseAlgorithmProvider(alg,0);return{};}std::ifstream in(std::filesystem::path(path),std::ios::binary);std::vector<unsigned char>b(1024*1024);while(in){in.read((char*)b.data(),b.size());auto c=in.gcount();if(c>0&&BCryptHashData(hash,b.data(),ULONG(c),0)<0){in.setstate(std::ios::badbit);break;}}bool ok=!in.bad()&&BCryptFinishHash(hash,digest.data(),DWORD(digest.size()),0)>=0;BCryptDestroyHash(hash);BCryptCloseAlgorithmProvider(alg,0);if(!ok)return{};std::ostringstream o;o<<std::hex<<std::setfill('0');for(auto x:digest)o<<std::setw(2)<<unsigned(x);return o.str();}
bool registered(std::wstring&exe,std::wstring&display){HKEY key=nullptr;if(RegOpenKeyExW(HKEY_LOCAL_MACHINE,L"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\RearSilver Avatar Suite",0,KEY_READ|KEY_WOW64_64KEY,&key)!=ERROR_SUCCESS)return false;wchar_t location[32768]{},version[256]{};DWORD type=0,bytes=sizeof(location);bool ok=RegQueryValueExW(key,L"InstallLocation",nullptr,&type,(BYTE*)location,&bytes)==ERROR_SUCCESS&&type==REG_SZ&&location[0];bytes=sizeof(version);type=0;ok=ok&&RegQueryValueExW(key,L"DisplayVersion",nullptr,&type,(BYTE*)version,&bytes)==ERROR_SUCCESS&&type==REG_SZ;RegCloseKey(key);if(!ok)return false;exe=(std::filesystem::path(location)/L"RearSilver Avatar Suite.exe").wstring();display=version;return GetFileAttributesW(exe.c_str())!=INVALID_FILE_ATTRIBUTES;}
}
int WINAPI wWinMain(HINSTANCE,HINSTANCE,PWSTR,int){Args a;if(!parse(a)){fail(L"The update handoff arguments were invalid.");return 2;}HANDLE process=OpenProcess(SYNCHRONIZE,FALSE,a.pid);if(!process){fail(L"Avatar Suite could not be monitored safely. The update was not started.");return 3;}std::wstring registeredExe,oldVersion;if(!registered(registeredExe,oldVersion)){CloseHandle(process);fail(L"The registered Avatar Suite installation could not be verified.");return 4;}HANDLE ready=OpenEventW(EVENT_MODIFY_STATE,FALSE,a.readyEvent.c_str());if(!ready){CloseHandle(process);fail(L"The update acknowledgement channel could not be opened.");return 5;}log(L"handoff-ready target="+a.version);SetEvent(ready);CloseHandle(ready);if(WaitForSingleObject(process,120000)!=WAIT_OBJECT_0){CloseHandle(process);fail(L"Avatar Suite did not close in time. The update was not installed.");return 6;}CloseHandle(process);
 std::error_code ec;if(!std::filesystem::is_regular_file(a.installer,ec)||std::filesystem::file_size(a.installer,ec)!=a.size||sha256(a.installer)!=a.sha){std::filesystem::remove(a.installer,ec);fail(L"The downloaded installer failed final size or SHA-256 verification.");return 7;}
 SHELLEXECUTEINFOW launch{};launch.cbSize=sizeof(launch);launch.fMask=SEE_MASK_NOCLOSEPROCESS;launch.lpVerb=L"runas";launch.lpFile=a.installer.c_str();launch.lpParameters=L"/S /UPDATEHANDOFF";launch.nShow=SW_SHOWNORMAL;if(!ShellExecuteExW(&launch)||!launch.hProcess){fail(L"Windows did not allow the installer to start. The update was not installed.");return 8;}WaitForSingleObject(launch.hProcess,INFINITE);DWORD code=1;GetExitCodeProcess(launch.hProcess,&code);CloseHandle(launch.hProcess);if(code){fail((L"The installer failed with exit code "+std::to_wstring(code)+L".").c_str());return 9;}
 std::wstring exe,display;if(!registered(exe,display)||display!=a.version){fail(L"Installation finished, but the registered DisplayVersion does not match the target version. Avatar Suite will not be relaunched automatically.");return 10;}std::filesystem::remove(a.installer,ec);auto folder=std::filesystem::path(exe).parent_path().wstring();if((INT_PTR)ShellExecuteW(nullptr,L"open",exe.c_str(),nullptr,folder.c_str(),SW_SHOWNORMAL)<=32){fail(L"The update installed successfully, but Avatar Suite could not be relaunched. Start it from the Start menu.");return 11;}log(L"update-complete version="+a.version);return 0;}
