#include <windows.h>
#include <shellapi.h>
#undef CreateWindow
#include <tlhelp32.h>
#include <d3d11_1.h>
#include <dxgi1_6.h>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>
struct SDL_Window; using SDL_WindowFlags=uint64_t; using SDL_PropertiesID=uint32_t;
union SDL_Event{uint32_t type;unsigned char padding[128];};
constexpr uint32_t SDL_INIT_VIDEO=0x20,SDL_EVENT_QUIT=0x100; constexpr SDL_WindowFlags SDL_WINDOW_RESIZABLE=0x20;
struct SDLApi{HMODULE m{};bool(__cdecl*Init)(uint32_t){};void(__cdecl*Quit)(){};const char*(__cdecl*GetError)(){};SDL_Window*(__cdecl*CreateWindow)(const char*,int,int,SDL_WindowFlags){};void(__cdecl*DestroyWindow)(SDL_Window*){};bool(__cdecl*PollEvent)(SDL_Event*){};bool(__cdecl*GetWindowSizeInPixels)(SDL_Window*,int*,int*){};SDL_PropertiesID(__cdecl*GetWindowProperties)(SDL_Window*){};void*(__cdecl*GetPointerProperty)(SDL_PropertiesID,const char*,void*){};template<class T>bool p(T&v,const char*n){v=reinterpret_cast<T>(GetProcAddress(m,n));return v!=nullptr;}bool open(){m=LoadLibraryW(L"C:\\Users\\Ben\\Desktop\\Streaming\\veadotube-mini-win-x64\\lib\\sdl3.dll");return m&&p(Init,"SDL_Init")&&p(Quit,"SDL_Quit")&&p(GetError,"SDL_GetError")&&p(CreateWindow,"SDL_CreateWindow")&&p(DestroyWindow,"SDL_DestroyWindow")&&p(PollEvent,"SDL_PollEvent")&&p(GetWindowSizeInPixels,"SDL_GetWindowSizeInPixels")&&p(GetWindowProperties,"SDL_GetWindowProperties")&&p(GetPointerProperty,"SDL_GetPointerProperty");}~SDLApi(){if(m)FreeLibrary(m);}};
static HANDLE lf=INVALID_HANDLE_VALUE;
static void log(const std::string&m){SYSTEMTIME t{};GetLocalTime(&t);char b[2048];int n=sprintf_s(b,"%04u-%02u-%02u %02u:%02u:%02u.%03u | %s\r\n",t.wYear,t.wMonth,t.wDay,t.wHour,t.wMinute,t.wSecond,t.wMilliseconds,m.c_str());if(lf!=INVALID_HANDLE_VALUE){DWORD w;WriteFile(lf,b,n,&w,nullptr);FlushFileBuffers(lf);}}
static void startLog(){wchar_t f[MAX_PATH]{},n[180];GetTempPathW(MAX_PATH,f);SYSTEMTIME t{};GetLocalTime(&t);swprintf_s(n,L"RearSilverAvatar-diagnostic18-%04u%02u%02u-%02u%02u%02u-%lu.log",t.wYear,t.wMonth,t.wDay,t.wHour,t.wMinute,t.wSecond,GetCurrentProcessId());lf=CreateFileW((std::wstring(f)+n).c_str(),GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);log("RearSilver Avatar diagnostic executable; process="+std::to_string(GetCurrentProcessId()));}

static DWORD findTargetProcess(const std::wstring& name){
	DWORD found=0;HANDLE snapshot=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);if(snapshot==INVALID_HANDLE_VALUE)return 0;
	PROCESSENTRY32W entry{};entry.dwSize=sizeof(entry);if(Process32FirstW(snapshot,&entry)){do{if(GetCurrentProcessId()!=entry.th32ProcessID&&_wcsicmp(entry.szExeFile,name.c_str())==0){found=entry.th32ProcessID;break;}}while(Process32NextW(snapshot,&entry));}CloseHandle(snapshot);return found;
}
struct ProbeDevice{ID3D11Device*device{};ID3D11DeviceContext*context{};DXGI_ADAPTER_DESC1 adapter{};};
static std::string utf8(const wchar_t*value);
struct AdapterCandidate{IDXGIAdapter1*adapter{};ID3D11Device*device{};ID3D11DeviceContext*context{};DXGI_ADAPTER_DESC1 desc{};D3D_FEATURE_LEVEL feature{};UINT outputs{};bool viable{};bool selfOpen{};UINT relatedOpen{};UINT relatedTotal{};};
static bool sameAdapterIdentity(const DXGI_ADAPTER_DESC1&a,const DXGI_ADAPTER_DESC1&b){return a.VendorId==b.VendorId&&a.DeviceId==b.DeviceId&&a.SubSysId==b.SubSysId;}
static bool sameLuid(const LUID&a,const LUID&b){return a.HighPart==b.HighPart&&a.LowPart==b.LowPart;}
static int chooseInteroperableAdapter(IDXGIAdapter1**selected){
	*selected=nullptr;IDXGIFactory1*factory{};HRESULT factoryResult=CreateDXGIFactory1(IID_PPV_ARGS(&factory));if(FAILED(factoryResult)){char b[160];sprintf_s(b,"Diagnostic 18: CreateDXGIFactory1 failed=0x%08X",(unsigned)factoryResult);log(b);return -1;}
	LUID defaultLuid{};bool haveDefault=false;ID3D11Device*defaultDevice{};ID3D11DeviceContext*defaultContext{};D3D_FEATURE_LEVEL defaultFeature{};HRESULT defaultResult=D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&defaultDevice,&defaultFeature,&defaultContext);if(SUCCEEDED(defaultResult)){IDXGIDevice*dxgi{};IDXGIAdapter*adapter{};DXGI_ADAPTER_DESC d{};if(SUCCEEDED(defaultDevice->QueryInterface(IID_PPV_ARGS(&dxgi)))&&SUCCEEDED(dxgi->GetAdapter(&adapter))&&SUCCEEDED(adapter->GetDesc(&d))){defaultLuid=d.AdapterLuid;haveDefault=true;}if(adapter)adapter->Release();if(dxgi)dxgi->Release();}if(defaultContext)defaultContext->Release();if(defaultDevice)defaultDevice->Release();
	char b[1000];sprintf_s(b,"Diagnostic 18 default hardware probe: create=0x%08X; feature=0x%04X; LUID=%ld:%lu; resolved=%u",(unsigned)defaultResult,(unsigned)defaultFeature,defaultLuid.HighPart,defaultLuid.LowPart,haveDefault);log(b);
	std::vector<AdapterCandidate> candidates;for(UINT index=0;;++index){IDXGIAdapter1*adapter{};if(factory->EnumAdapters1(index,&adapter)==DXGI_ERROR_NOT_FOUND)break;AdapterCandidate c{};c.adapter=adapter;adapter->GetDesc1(&c.desc);for(UINT oi=0;;++oi){IDXGIOutput*out{};if(adapter->EnumOutputs(oi,&out)==DXGI_ERROR_NOT_FOUND)break;c.outputs++;out->Release();}bool hardware=(c.desc.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)==0;HRESULT create=hardware?D3D11CreateDevice(adapter,D3D_DRIVER_TYPE_UNKNOWN,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&c.device,&c.feature,&c.context):E_FAIL;c.viable=hardware&&SUCCEEDED(create);sprintf_s(b,"Diagnostic 18 candidate %u: name=%s; LUID=%ld:%lu; vendor=%u; device=%u; subsystem=%u; revision=%u; outputs=%u; flags=0x%08X; hardware=%u; create=0x%08X; feature=0x%04X; default=%u",index,utf8(c.desc.Description).c_str(),c.desc.AdapterLuid.HighPart,c.desc.AdapterLuid.LowPart,c.desc.VendorId,c.desc.DeviceId,c.desc.SubSysId,c.desc.Revision,c.outputs,c.desc.Flags,hardware,(unsigned)create,(unsigned)c.feature,haveDefault&&sameLuid(c.desc.AdapterLuid,defaultLuid));log(b);candidates.push_back(c);}
	std::vector<std::vector<bool>> matrix(candidates.size(),std::vector<bool>(candidates.size(),false));for(size_t from=0;from<candidates.size();++from){auto&source=candidates[from];if(!source.viable)continue;D3D11_TEXTURE2D_DESC td{};td.Width=64;td.Height=64;td.MipLevels=1;td.ArraySize=1;td.Format=DXGI_FORMAT_R8G8B8A8_UNORM;td.SampleDesc.Count=1;td.Usage=D3D11_USAGE_DEFAULT;td.BindFlags=D3D11_BIND_SHADER_RESOURCE;td.MiscFlags=D3D11_RESOURCE_MISC_SHARED;ID3D11Texture2D*texture{};HRESULT createTexture=source.device->CreateTexture2D(&td,nullptr,&texture);HANDLE handle{};HRESULT getHandle=E_FAIL;IDXGIResource*resource{};if(SUCCEEDED(createTexture)&&texture&&SUCCEEDED(texture->QueryInterface(IID_PPV_ARGS(&resource))))getHandle=resource->GetSharedHandle(&handle);sprintf_s(b,"Diagnostic 18 resource %zu: CreateTexture2D=0x%08X; GetSharedHandle=0x%08X; handle=0x%p",from,(unsigned)createTexture,(unsigned)getHandle,handle);log(b);if(handle){for(size_t to=0;to<candidates.size();++to){if(!candidates[to].viable)continue;ID3D11Texture2D*opened{};HRESULT open=candidates[to].device->OpenSharedResource(handle,IID_PPV_ARGS(&opened));matrix[from][to]=SUCCEEDED(open)&&opened;sprintf_s(b,"Diagnostic 18 matrix: created-on=%zu; opened-on=%zu; related=%u; result=0x%08X; success=%u",from,to,(unsigned)sameAdapterIdentity(source.desc,candidates[to].desc),(unsigned)open,(unsigned)(matrix[from][to]?1:0));log(b);if(opened)opened->Release();}}if(resource)resource->Release();if(texture)texture->Release();}
	int defaultIndex=-1;for(size_t i=0;i<candidates.size();++i)if(haveDefault&&sameLuid(candidates[i].desc.AdapterLuid,defaultLuid)){defaultIndex=(int)i;break;}for(size_t from=0;from<candidates.size();++from){auto&candidate=candidates[from];if(!candidate.viable)continue;candidate.selfOpen=matrix[from][from];for(size_t to=0;to<candidates.size();++to)if(candidates[to].viable&&sameAdapterIdentity(candidate.desc,candidates[to].desc)){candidate.relatedTotal++;if(matrix[from][to])candidate.relatedOpen++;}sprintf_s(b,"Diagnostic 18 score %zu: viable=%u; self-open=%u; related-open=%u/%u; default=%u",from,candidate.viable,candidate.selfOpen,candidate.relatedOpen,candidate.relatedTotal,(int)from==defaultIndex);log(b);}
	int choice=(defaultIndex>=0&&candidates[defaultIndex].viable&&candidates[defaultIndex].selfOpen)?defaultIndex:-1;if(choice>=0){for(size_t i=0;i<candidates.size();++i)if(candidates[i].viable&&candidates[i].selfOpen&&sameAdapterIdentity(candidates[i].desc,candidates[choice].desc)&&candidates[i].relatedOpen>candidates[choice].relatedOpen)choice=(int)i;}else{for(size_t i=0;i<candidates.size();++i)if(candidates[i].viable&&candidates[i].selfOpen&&(choice<0||candidates[i].relatedOpen>candidates[choice].relatedOpen))choice=(int)i;}
	if(choice>=0){candidates[choice].adapter->AddRef();*selected=candidates[choice].adapter;sprintf_s(b,"Diagnostic 18 selected candidate %d: LUID=%ld:%lu; related-open=%u/%u; default=%u; reason=%s",choice,candidates[choice].desc.AdapterLuid.HighPart,candidates[choice].desc.AdapterLuid.LowPart,candidates[choice].relatedOpen,candidates[choice].relatedTotal,choice==defaultIndex,choice==defaultIndex?"ordinary default won or tied":"strictly greater related-adapter shared-resource interoperability");log(b);}else log("Diagnostic 18 found no viable self-sharing hardware adapter");
	for(auto&candidate:candidates){if(candidate.context)candidate.context->Release();if(candidate.device)candidate.device->Release();if(candidate.adapter)candidate.adapter->Release();}factory->Release();return choice;
}
static std::string elapsedText(LARGE_INTEGER start,LARGE_INTEGER frequency){LARGE_INTEGER now{};QueryPerformanceCounter(&now);char b[80];sprintf_s(b,"+%.3f ms",double(now.QuadPart-start.QuadPart)*1000.0/double(frequency.QuadPart));return b;}
static std::string utf8(const wchar_t*value){if(!value)return{};int bytes=WideCharToMultiByte(CP_UTF8,0,value,-1,nullptr,0,nullptr,nullptr);std::string result(bytes?bytes:1,'\0');if(bytes>1)WideCharToMultiByte(CP_UTF8,0,value,-1,result.data(),bytes,nullptr,nullptr);if(!result.empty()&&result.back()=='\0')result.pop_back();return result;}
static int inspectOBSTexture(const std::wstring& processName){
	const DWORD pid=findTargetProcess(processName);if(!pid){MessageBoxW(nullptr,(L"Could not find a running process named "+processName+L".").c_str(),L"Diagnostic 15",MB_OK|MB_ICONERROR);return 10;}
	log("Diagnostic build 15 external OBS capture-texture inspector; target="+std::string(processName.begin(),processName.end())+"; pid="+std::to_string(pid));
	LARGE_INTEGER frequency{},start{};QueryPerformanceFrequency(&frequency);QueryPerformanceCounter(&start);
	std::vector<ProbeDevice> devices;IDXGIFactory1*factory{};if(SUCCEEDED(CreateDXGIFactory1(IID_PPV_ARGS(&factory)))){for(UINT index=0;;++index){IDXGIAdapter1*adapter{};if(factory->EnumAdapters1(index,&adapter)==DXGI_ERROR_NOT_FOUND)break;ProbeDevice probe{};adapter->GetDesc1(&probe.adapter);D3D_FEATURE_LEVEL actual{};HRESULT result=D3D11CreateDevice(adapter,D3D_DRIVER_TYPE_UNKNOWN,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&probe.device,&actual,&probe.context);char b[900];sprintf_s(b,"Probe adapter %u: name=%s; LUID=%ld:%lu; vendor=%u; device=%u; subsystem=%u; revision=%u; dedicated video=%llu; dedicated system=%llu; shared system=%llu; flags=0x%08X; create=0x%08X; feature=0x%04X",index,utf8(probe.adapter.Description).c_str(),probe.adapter.AdapterLuid.HighPart,probe.adapter.AdapterLuid.LowPart,probe.adapter.VendorId,probe.adapter.DeviceId,probe.adapter.SubSysId,probe.adapter.Revision,(unsigned long long)probe.adapter.DedicatedVideoMemory,(unsigned long long)probe.adapter.DedicatedSystemMemory,(unsigned long long)probe.adapter.SharedSystemMemory,probe.adapter.Flags,(unsigned)result,(unsigned)actual);log(b);for(UINT outputIndex=0;;++outputIndex){IDXGIOutput*output{};if(adapter->EnumOutputs(outputIndex,&output)==DXGI_ERROR_NOT_FOUND)break;DXGI_OUTPUT_DESC od{};output->GetDesc(&od);sprintf_s(b,"  output %u: name=%s; attached=%u; desktop=(%ld,%ld)-(%ld,%ld); rotation=%u",outputIndex,utf8(od.DeviceName).c_str(),od.AttachedToDesktop,od.DesktopCoordinates.left,od.DesktopCoordinates.top,od.DesktopCoordinates.right,od.DesktopCoordinates.bottom,(unsigned)od.Rotation);log(b);output->Release();}if(SUCCEEDED(result))devices.push_back(probe);else{if(probe.context)probe.context->Release();if(probe.device)probe.device->Release();}adapter->Release();}IDXGIFactory6*factory6{};if(SUCCEEDED(factory->QueryInterface(IID_PPV_ARGS(&factory6)))){const DXGI_GPU_PREFERENCE preferences[]={DXGI_GPU_PREFERENCE_UNSPECIFIED,DXGI_GPU_PREFERENCE_MINIMUM_POWER,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE};const char*names[]={"unspecified","minimum-power","high-performance"};for(UINT p=0;p<3;++p){for(UINT index=0;;++index){IDXGIAdapter1*adapter{};if(factory6->EnumAdapterByGpuPreference(index,preferences[p],IID_PPV_ARGS(&adapter))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};adapter->GetDesc1(&desc);char preferenceLine[500];sprintf_s(preferenceLine,"GPU preference %s[%u]: name=%s; LUID=%ld:%lu",names[p],index,utf8(desc.Description).c_str(),desc.AdapterLuid.HighPart,desc.AdapterLuid.LowPart);log(preferenceLine);adapter->Release();}}factory6->Release();}factory->Release();}
	HANDLE process=OpenProcess(SYNCHRONIZE,FALSE,pid);DWORD lastMap=0,lastHandle=0;bool mappingWasPresent=false,handleWasValid=false;ULONGLONG deadline=GetTickCount64()+30000,lastHeartbeat=0;
	while(GetTickCount64()<deadline&&process&&WaitForSingleObject(process,0)==WAIT_TIMEOUT){
		std::wstring infoName=L"CaptureHook_HookInfo"+std::to_wstring(pid);HANDLE infoMap=OpenFileMappingW(FILE_MAP_READ,FALSE,infoName.c_str());
		if(!infoMap){if(mappingWasPresent){log(elapsedText(start,frequency)+" hook-info mapping disappeared");mappingWasPresent=false;}Sleep(1);continue;}mappingWasPresent=true;unsigned char bytes[648]{};void*view=MapViewOfFile(infoMap,FILE_MAP_READ,0,0,sizeof(bytes));if(view){memcpy(bytes,view,sizeof(bytes));UnmapViewOfFile(view);}CloseHandle(infoMap);if(!view){Sleep(1);continue;}
		auto u32=[&](size_t offset){DWORD value{};memcpy(&value,bytes+offset,sizeof(value));return value;};DWORD type=u32(8),window=u32(12),format=u32(16),cx=u32(20),cy=u32(24),mapId=u32(40),mapBytes=u32(44);
		if(type!=1||!window||!mapId){Sleep(1);continue;}std::wstring textureName=L"CaptureHook_Texture_"+std::to_wstring(window)+L"_"+std::to_wstring(mapId);HANDLE textureMap=OpenFileMappingW(FILE_MAP_READ,FALSE,textureName.c_str());DWORD handleValue=0;if(textureMap){void*textureView=MapViewOfFile(textureMap,FILE_MAP_READ,0,0,sizeof(DWORD));if(textureView){memcpy(&handleValue,textureView,sizeof(handleValue));UnmapViewOfFile(textureView);}CloseHandle(textureMap);}
		if(mapId!=lastMap||handleValue!=lastHandle){char b[700];sprintf_s(b,"%s publication: type=%lu; window=%lu; hook format=%lu; size=%lux%lu; map id=%lu; map bytes=%lu; handle=0x%08lX; mapping=%s",elapsedText(start,frequency).c_str(),type,window,format,cx,cy,mapId,mapBytes,handleValue,handleValue?"open":"unavailable");log(b);lastMap=mapId;lastHandle=handleValue;handleWasValid=false;}
		bool anyValid=false;if(handleValue){for(size_t index=0;index<devices.size();++index){ID3D11Texture2D*texture{};HRESULT result=devices[index].device->OpenSharedResource(reinterpret_cast<HANDLE>(static_cast<uintptr_t>(handleValue)),IID_PPV_ARGS(&texture));if(SUCCEEDED(result)&&texture){anyValid=true;if(!handleWasValid){D3D11_TEXTURE2D_DESC desc{};texture->GetDesc(&desc);char b[900];sprintf_s(b,"%s adapter %zu OpenSharedResource=0x%08X; texture: width=%u; height=%u; mips=%u; array=%u; format=%u; samples=%u; quality=%u; usage=%u; bind=0x%08X; CPU access=0x%08X; misc=0x%08X",elapsedText(start,frequency).c_str(),index,(unsigned)result,desc.Width,desc.Height,desc.MipLevels,desc.ArraySize,(unsigned)desc.Format,desc.SampleDesc.Count,desc.SampleDesc.Quality,(unsigned)desc.Usage,desc.BindFlags,desc.CPUAccessFlags,desc.MiscFlags);log(b);}texture->Release();}else if(!handleWasValid){char b[240];sprintf_s(b,"%s adapter %zu OpenSharedResource failed=0x%08X",elapsedText(start,frequency).c_str(),index,(unsigned)result);log(b);}}}
		if(handleWasValid&&!anyValid)log(elapsedText(start,frequency)+" published handle changed from valid to invalid while map id remained "+std::to_string(mapId));handleWasValid=anyValid;
		if(GetTickCount64()-lastHeartbeat>=2000){log(elapsedText(start,frequency)+" lifetime: map id="+std::to_string(mapId)+"; handle=0x"+[] (DWORD v){char b[16];sprintf_s(b,"%08lX",v);return std::string(b);}(handleValue)+"; valid="+std::to_string(anyValid));lastHeartbeat=GetTickCount64();}Sleep(1);
	}
	if(process)CloseHandle(process);for(auto&probe:devices){probe.context->Release();probe.device->Release();}log(elapsedText(start,frequency)+" inspection finished");MessageBoxW(nullptr,L"Diagnostic 15 inspection finished. The timestamped log is in your Temp folder.",L"Diagnostic 15",MB_OK|MB_ICONINFORMATION);return 0;
}
int WINAPI wWinMain(HINSTANCE,HINSTANCE,PWSTR,int){startLog();int argc=0;LPWSTR* argv=CommandLineToArgvW(GetCommandLineW(),&argc);if(argv&&argc>=3&&std::wstring(argv[1])==L"--inspect"){std::wstring target=argv[2];LocalFree(argv);int result=inspectOBSTexture(target);if(lf!=INVALID_HANDLE_VALUE)CloseHandle(lf);return result;}if(argv)LocalFree(argv);log("Diagnostic build 18 renderer mode; experimental shared-resource interoperability matrix and dynamic adapter selection");IDXGIAdapter1*selectedAdapter{};int selectedIndex=chooseInteroperableAdapter(&selectedAdapter);if(selectedIndex<0||!selectedAdapter){log("Diagnostic 18 cannot start renderer because adapter selection failed");return 7;}SDLApi s;if(!s.open()||!s.Init(SDL_INIT_VIDEO)){selectedAdapter->Release();return 1;}SDL_Window*win=s.CreateWindow("RearSilver Avatar - Diagnostic 18 - Adapter Interoperability Matrix",960,720,SDL_WINDOW_RESIZABLE);if(!win){selectedAdapter->Release();return 2;}HWND hwnd=(HWND)s.GetPointerProperty(s.GetWindowProperties(win),"SDL.window.win32.hwnd",nullptr);if(!hwnd){log("SDL HWND unavailable");selectedAdapter->Release();return 3;}
	ID3D11Device*d{};ID3D11DeviceContext*c{};IDXGISwapChain*sc{};ID3D11RenderTargetView*r{};ID3D11DeviceContext1*c1{};
	DXGI_SWAP_CHAIN_DESC x{};x.BufferDesc.Width=960;x.BufferDesc.Height=720;x.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;x.SampleDesc.Count=1;x.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;x.BufferCount=1;x.OutputWindow=hwnd;x.Windowed=TRUE;x.SwapEffect=DXGI_SWAP_EFFECT_DISCARD;x.Flags=0;D3D_FEATURE_LEVEL ls[]={D3D_FEATURE_LEVEL_11_1,D3D_FEATURE_LEVEL_11_0,D3D_FEATURE_LEVEL_10_1,D3D_FEATURE_LEVEL_10_0},fl{};HRESULT hr=D3D11CreateDeviceAndSwapChain(selectedAdapter,D3D_DRIVER_TYPE_UNKNOWN,nullptr,0,ls,4,D3D11_SDK_VERSION,&x,&sc,&d,&fl,&c);selectedAdapter->Release();selectedAdapter=nullptr;if(FAILED(hr)){char b[100];sprintf_s(b,"Create failed 0x%08X",(unsigned)hr);log(b);return 5;}
	DXGI_SWAP_CHAIN_DESC initial{};sc->GetDesc(&initial);char audit[700];sprintf_s(audit,"Initial audit: feature=0x%04X; device flags=0x%08X; format=%u; samples=%u; usage=%u; buffers=%u; windowed=%u; swap effect=%u; flags=%u",(unsigned)fl,d->GetCreationFlags(),(unsigned)initial.BufferDesc.Format,initial.SampleDesc.Count,initial.BufferUsage,initial.BufferCount,initial.Windowed,(unsigned)initial.SwapEffect,initial.Flags);log(audit);
	hr=sc->ResizeBuffers(2,960,720,DXGI_FORMAT_R8G8B8A8_UNORM,0);if(FAILED(hr)){char b[100];sprintf_s(b,"Initial ResizeBuffers failed 0x%08X",(unsigned)hr);log(b);return 6;}c->QueryInterface(IID_PPV_ARGS(&c1));ID3D11Texture2D*bb{};sc->GetBuffer(0,IID_PPV_ARGS(&bb));d->CreateRenderTargetView(bb,nullptr,&r);bb->Release();IDXGIDevice*xd{};IDXGIAdapter*a{};DXGI_ADAPTER_DESC ad{};if(SUCCEEDED(d->QueryInterface(IID_PPV_ARGS(&xd)))&&SUCCEEDED(xd->GetAdapter(&a)))a->GetDesc(&ad);DXGI_SWAP_CHAIN_DESC q{};sc->GetDesc(&q);sprintf_s(audit,"Post-resize audit: LUID=%ld:%lu; format=%u; samples=%u; usage=%u; buffers=%u; windowed=%u; swap effect=%u; flags=%u",ad.AdapterLuid.HighPart,ad.AdapterLuid.LowPart,(unsigned)q.BufferDesc.Format,q.SampleDesc.Count,q.BufferUsage,q.BufferCount,q.Windowed,(unsigned)q.SwapEffect,q.Flags);log(audit);
	bool run=true;uint64_t frames=0;ULONGLONG report=GetTickCount64();while(run){SDL_Event e{};while(s.PollEvent(&e))if(e.type==SDL_EVENT_QUIT)run=false;int w=960,h=720;s.GetWindowSizeInPixels(win,&w,&h);sc->GetDesc(&q);if((int)q.BufferDesc.Width!=w||(int)q.BufferDesc.Height!=h){c->OMSetRenderTargets(0,nullptr,nullptr);r->Release();sc->ResizeBuffers(2,w,h,DXGI_FORMAT_R8G8B8A8_UNORM,0);sc->GetBuffer(0,IID_PPV_ARGS(&bb));d->CreateRenderTargetView(bb,nullptr,&r);bb->Release();}float z[4]={0,0,0,0};c->ClearRenderTargetView(r,z);float bob=std::sin(float(GetTickCount64()%4000)/4000*6.2831853f)*45;if(c1){D3D11_RECT rc{LONG(w*.36f),LONG(h*.24f+bob),LONG(w*.64f),LONG(h*.74f+bob)};float g[4]={.22f,.27f,.34f,1};c1->ClearView(r,g,&rc,1);D3D11_RECT fc{LONG(w*.405f),LONG(h*.31f+bob),LONG(w*.595f),LONG(h*.52f+bob)};float p[4]={.78f,.83f,.9f,1};c1->ClearView(r,p,&fc,1);}sc->Present(1,0);frames++;ULONGLONG now=GetTickCount64();if(now-report>=2000){log("Render progress: frame="+std::to_string(frames)+"; hook="+std::to_string(GetModuleHandleW(L"graphics-hook64.dll")!=nullptr));report=now;}Sleep(1);}if(a)a->Release();if(xd)xd->Release();if(c1)c1->Release();r->Release();sc->Release();c->Release();d->Release();s.DestroyWindow(win);s.Quit();if(lf!=INVALID_HANDLE_VALUE)CloseHandle(lf);return 0;}
