#pragma once
#include <windows.h>
#include <string>

constexpr UINT kAvatarSettingsChoosePngMessage = WM_APP + 10;
constexpr UINT kAvatarSettingsReadyMessage = WM_APP + 11;
constexpr UINT kAvatarSettingsChooseReactionPngMessage = WM_APP + 12;
constexpr UINT kAvatarSettingsPreviewReactionMessage = WM_APP + 13;
constexpr UINT kAvatarSettingsSelectMicrophoneMessage = WM_APP + 14;
constexpr UINT kAvatarSettingsReactionThresholdMessage = WM_APP + 15;
constexpr UINT kAvatarSettingsReleaseDelayMessage = WM_APP + 16;
constexpr UINT kAvatarSettingsChoosePrimaryBlinkMessage = WM_APP + 17;
constexpr UINT kAvatarSettingsChooseReactionBlinkMessage = WM_APP + 18;
constexpr UINT kAvatarSettingsBlinkEnabledMessage = WM_APP + 19;
constexpr UINT kAvatarSettingsBlinkMinimumMessage = WM_APP + 22;
constexpr UINT kAvatarSettingsBlinkMaximumMessage = WM_APP + 23;
constexpr UINT kAvatarSettingsBlinkDurationMessage = WM_APP + 24;
constexpr UINT kAvatarSettingsBounceEnabledMessage = WM_APP + 25;
constexpr UINT kAvatarSettingsBounceHeightMessage = WM_APP + 26;
constexpr UINT kAvatarSettingsBounceDurationMessage = WM_APP + 27;
constexpr UINT kAvatarSettingsPreviewBounceMessage = WM_APP + 28;
constexpr UINT kAvatarSettingsCalibrateNoiseMessage = WM_APP + 29;
constexpr UINT kAvatarSettingsNoiseSensitivityMessage = WM_APP + 30;
constexpr UINT kAvatarSettingsUseDefaultPrimaryMessage = WM_APP + 31;
constexpr UINT kAvatarSettingsUseDefaultReactionMessage = WM_APP + 32;
constexpr UINT kAvatarSettingsRemovePrimaryBlinkMessage = WM_APP + 33;
constexpr UINT kAvatarSettingsRemoveReactionBlinkMessage = WM_APP + 34;
constexpr UINT kAvatarSettingsEffectStackMessage = WM_APP + 35;
constexpr UINT kAvatarSettingsBreathingEnabledMessage = WM_APP + 36;
constexpr UINT kAvatarSettingsBreathingModeMessage = WM_APP + 37;
constexpr UINT kAvatarSettingsBreathingIdleMessage = WM_APP + 38;
constexpr UINT kAvatarSettingsBreathingReactionMessage = WM_APP + 39;
constexpr UINT kAvatarSettingsBreathingCycleMessage = WM_APP + 40;
constexpr UINT kAvatarSettingsSquashEnabledMessage = WM_APP + 41;
constexpr UINT kAvatarSettingsSquashIntensityMessage = WM_APP + 42;
constexpr UINT kAvatarSettingsSquashDurationMessage = WM_APP + 43;
constexpr UINT kAvatarSettingsPreviewSquashMessage = WM_APP + 44;
constexpr UINT kAvatarSettingsShakeEnabledMessage = WM_APP + 45;
constexpr UINT kAvatarSettingsShakeIntensityMessage = WM_APP + 46;
constexpr UINT kAvatarSettingsShakeSpeedMessage = WM_APP + 47;
constexpr UINT kAvatarSettingsShakeDirectionMessage = WM_APP + 48;
constexpr UINT kAvatarSettingsShakeWobbleMessage = WM_APP + 49;
constexpr UINT kAvatarSettingsPreviewShakeMessage = WM_APP + 50;
constexpr UINT kAvatarSettingsBrightnessEnabledMessage = WM_APP + 51;
constexpr UINT kAvatarSettingsBrightnessIdleMessage = WM_APP + 52;
constexpr UINT kAvatarSettingsBrightnessReactionMessage = WM_APP + 53;
constexpr UINT kAvatarSettingsBrightnessTransitionMessage = WM_APP + 54;
constexpr UINT kAvatarSettingsPreviewBrightnessMessage = WM_APP + 55;
constexpr UINT kAvatarSettingsFloatEnabledMessage = WM_APP + 56;
constexpr UINT kAvatarSettingsFloatModeMessage = WM_APP + 57;
constexpr UINT kAvatarSettingsFloatHeightMessage = WM_APP + 58;
constexpr UINT kAvatarSettingsFloatCycleMessage = WM_APP + 60;
constexpr UINT kAvatarSettingsFloatDirectionMessage = WM_APP + 61;
constexpr UINT kAvatarSettingsFloatDriftMessage = WM_APP + 62;
constexpr UINT kAvatarSettingsPreviewFloatMessage = WM_APP + 63;
constexpr UINT kAvatarSettingsTiltEnabledMessage = WM_APP + 64;
constexpr UINT kAvatarSettingsTiltAngleMessage = WM_APP + 65;
constexpr UINT kAvatarSettingsTiltDirectionMessage = WM_APP + 66;
constexpr UINT kAvatarSettingsTiltTransitionMessage = WM_APP + 67;
constexpr UINT kAvatarSettingsPreviewTiltMessage = WM_APP + 68;

bool showAvatarSettingsWindow(HWND owner);
bool isAvatarSettingsWindowVisible();
void postAvatarSettingsMessage(const std::wstring &message);
void setAvatarSettingsPreviewImage(unsigned slot, const std::wstring &path);
void shutdownAvatarSettingsWindow();
