#include "update_version.hpp"
#include <algorithm>
#include <cctype>
#include <limits>
#include <vector>
namespace { struct I{bool n=false;unsigned long long v=0;std::string t;};struct V{unsigned long long a=0,b=0,c=0;std::vector<I>p;};
bool num(const std::string&s,unsigned long long&v){if(s.empty()||(s.size()>1&&s[0]=='0'))return false;v=0;for(unsigned char c:s){if(!std::isdigit(c))return false;unsigned d=c-'0';if(v>(std::numeric_limits<unsigned long long>::max()-d)/10)return false;v=v*10+d;}return true;}
std::vector<std::string> split(const std::string&s,char d){std::vector<std::string>o;size_t b=0;for(;;){size_t e=s.find(d,b);o.push_back(s.substr(b,e==std::string::npos?e:e-b));if(e==std::string::npos)return o;b=e+1;}}
bool parse(const std::string&r,V&v){if(r.empty())return false;size_t plus=r.find('+');if(plus!=std::string::npos){auto q=r.substr(plus+1);if(q.empty()||r.find('+',plus+1)!=std::string::npos)return false;for(auto&x:split(q,'.')){if(x.empty())return false;for(unsigned char c:x)if(!std::isalnum(c)&&c!='-')return false;}}auto base=r.substr(0,plus);size_t dash=base.find('-');auto core=split(base.substr(0,dash),'.');if(core.size()!=3||!num(core[0],v.a)||!num(core[1],v.b)||!num(core[2],v.c))return false;if(dash==std::string::npos)return true;for(auto&x:split(base.substr(dash+1),'.')){if(x.empty())return false;for(unsigned char c:x)if(!std::isalnum(c)&&c!='-')return false;I i;i.t=x;bool digits=std::all_of(x.begin(),x.end(),[](unsigned char c){return std::isdigit(c)!=0;});i.n=num(x,i.v);if(digits&&!i.n)return false;v.p.push_back(i);}return true;}int cmp(unsigned long long a,unsigned long long b){return a<b?-1:a>b?1:0;}}
bool compareUpdateVersions(const std::string&a,const std::string&b,int&o){V x,y;if(!parse(a,x)||!parse(b,y))return false;o=cmp(x.a,y.a);if(!o)o=cmp(x.b,y.b);if(!o)o=cmp(x.c,y.c);if(o)return true;if(x.p.empty()||y.p.empty()){o=x.p.empty()==y.p.empty()?0:x.p.empty()?1:-1;return true;}size_t n=std::min(x.p.size(),y.p.size());for(size_t k=0;k<n;++k){auto&l=x.p[k];auto&r=y.p[k];o=l.n&&r.n?cmp(l.v,r.v):l.n!=r.n?(l.n?-1:1):l.t<r.t?-1:l.t>r.t?1:0;if(o)return true;}o=cmp(x.p.size(),y.p.size());return true;}
std::string updateChannelSlug(const std::string&s){std::string o;for(unsigned char c:s){if(std::isalnum(c))o.push_back(char(std::tolower(c)));else if(!o.empty()&&o.back()!='-')o.push_back('-');}while(!o.empty()&&o.back()=='-')o.pop_back();return o;}
